on: [push]

jobs:
  nikola_build:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: set git config
      run: |
        git config --global user.email 105642861+Amikumu@users.noreply.github.com
        git config --global user.name Amikumu
        git config -l
    - name: Check out
      uses: actions/checkout@v3
    - name: get commit message
      run: |
        echo Commit MSG = $commitmsg
    - run: ruby messages.rb
    - run: ruby split-translations.rb
    - run: ruby pages.rb
    - name: Build and Deploy Nikola
      uses: amikumu/nikola-action@main
      with:
        dry_run: false
