on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
	- run: git config user.name "Amikumu"
	- run: git config user.email "help@amikumu.com"
    - run: ruby split-translations.rb
    - run: ruby pages.rb
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v4
      with:
        dry_run: false
